[package]
name = "monolithic_graph_named"
type = "bin"
authors = [""]
# Verbatim re-host of `transform/tests/snapshots/graph_named.*`.

[dependencies]
consts = { path = "../../noir/lib/consts" }
types = { path = "../../noir/lib/types" }
utils = { path = "../../noir/lib/utils" }
